export const actionTypes = {
  REGISTER_EMPLOYER: "REGISTER_EMPLOYER",
  LOGIN_EMPLOYER: "LOGIN_EMPLOYER",
  SIGN_OUT_EMPLOYER: "SIGN_OUT_EMPLOYER",
  DELETE_EMPLOYER: "DELETE_EMPLOYER",
  ALL_EMPLOYERS: "ALL_EMPLOYERS",
  REGISTER_TECHNICIAN: "REGISTER_TECHNICIAN",
  LOGIN_TECHNICIAN: "LOGIN_TECHNICIAN",
  SIGN_OUT_TECHNICIAN: "SIGN_OUT_TECHNICIAN",
  DELETE_TECHNICIAN: "DELETE_TECHNICIAN",
  ONE_TECHNICIAN: "ONE_TECHNICIAN",
  ALL_TECHNICIANS: "ALL_TECHNICIANS",
  SAVE_CHAT : 'SAVE_CHAT',
  GET_ROOM_CHAT : 'GET_ROOM_CHAT',
  ERROR: 'ERROR'
}